spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/2631478675/spring_cloud_config
          username: 2634178675
          password: lintong1860
#          basedir: 可以自定义本地仓库
          ####默认的本地仓库file:/var/folders/zk/c98xrbxd7kd65bh_69bwdjn80000gn/T/config-repo-7340455714816032151/product.yml
server:
  port: 8200

eureka:
  instance:
    prefer-ip-address: true # 注册服务的时候使用服务的ip地址
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka